package com.vio.exceptions;

/**
 * Created by IntelliJ IDEA.
 * User: nikelin
 * Date: Mar 11, 2010
 * Time: 11:59:12 AM
 * To change this template use File | Settings | File Templates.
 */
public enum ErrorCode {
    EXCEPTION_INVALID_API_KEY,
    EXCEPTION_AUTHENTICATION_FAIL,
    EXCEPTION_INACTIVE_API_KEY,
    EXCEPTION_EXPIRED_API_KEY,
    EXCEPTION_REQUEST_PROCESSING_ERROR,
    EXCEPTION_REQUEST_INTERFACE_NOT_EXISTS,
    EXCEPTION_REQUEST_METHOD_NOT_EXISTS,
    EXCEPTION_SERVER_ALREADY_BINDED,
    EXCEPTION_INTERNAL,
    EXCEPTION_SERVER_ALREADY_STARTED,
    EXCEPTION_MISSED_REQUEST_HEAD ,
    EXCEPTION_WRONG_REQUEST_HEADERS ,
    EXCEPTION_MISSED_REQUEST_BODY,
    EXCEPTION_WRONG_REQUEST_BODY,
    EXCEPTION_WRONG_REQUEST,
    EXCEPTION_GROUP_NOT_EXISTS,
    EXCEPTION_GROUP_ALREADY_EXISTS,
    EXCEPTION_USER_NOT_EXISTS,
    EXCEPTION_ACCESS_DENIED,
    EXCEPTION_RECONNECT,
    EXCEPTION_RECORD_ALREADY_EXISTS,
    EXCEPTION_RECORD_NOT_EXISTS,
    EXCEPTION_INVALID_RECORD,
    EXCEPTION_All_ATTEMPTS_HAVE_BEEN_USED
}
